version: "3"
services:
    # web_gui:
    #     container_name: "web_gui"
    #     build: "./WebGUI"
    #     ports:
    #         - "3000:3000"

    aspnetcore_sensor:
        container_name: "sensor"
        image: aspnetcore_sensor:latest
        build: "./SocialEvolutionSensorAPI"
        ports:
            - "55834:55834"

    aspnetcore_collector:
        container_name: "collector"
        image: aspnetcore_collector:latest
        build: "./SocialEvolutionDataCollector"
        ports:
            - "55835:55835"
        environment:
            - DATA_COLLECTOR_DB_URI="mongodb+srv://collector_node:collector_node@socialevolutioncluster-kde4s.mongodb.net/test?retryWrites=true"

    aspnetcore_call_statistics:
        container_name: "call_statistics"
        image: aspnetcore_call_statistics:latest
        build: "./Statistics/CallStatistics/CallStatistics/"
        ports:
            - "55836:55836"

    nodejs_message_statistics:
        container_name: "message_statistics"
        image: nodejs_message_statistics:latest
        build: "./Statistics/MessageStatistics/"
        ports:
            - "55837:55837"

    mqtt-publisher:
        container_name: "mqtt_publisher"
        image: mqtt-publisher:latest
        build: "./Statistics/mqtt-publisher/"
        ports:
            - 34567:34567
